article_app/urls.py
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('', main_page, name='main_page'),
    path('contact/', contact, name='contact'),
    path('about_journal/', about_journal, name='about_journal'),
    path('editor_board/', editor_board, name='editor_board'),
    path('guide_for_authors/', guide_for_authors, name='guide_for_authors'),
    path('load_sidebar_menus/', load_sidebar_menus, name='load_sidebar_menus'),
    path('load_navbar_menus/', load_navbar_menus, name='load_navbar_menus'),

    path('article/create/', create_article, name='create_article'),
    path('article/view/<int:pk>/', article_view, name='article_view'),
    path('article/edit/<int:pk>/', update_article, name='update_article'),
    path('article/delete/<int:pk>/', delete_article, name='delete_article'),
    path('article/file/create/<int:pk>/', create_article_file, name='create_article_file'),

    path('authors/<int:pk>/', get_article_authors, name='get_article_authors'),
    path('author/add/<int:pk>/', add_author, name='add_author'),
    path('author/edit/<int:pk>/', edit_author, name='edit_author'),
    path('author/delete/<int:pk>/', delete_author, name='delete_author'),

    # Article Status
    path('article_status/', article_status_list, name='article_status_list'),
    path('article_status_update/<int:pk>/', article_status_update, name='article_status_update'),
    path('article_status_delete/<int:pk>/', article_status_delete, name='article_status_delete'),

    path('send_message/<int:pk>/<int:user_id>/', send_message, name='send_message'),

    # Sections
    path('sections/', list_sections, name='sections'),
    path('section_delete/<int:pk>/', section_delete, name='section_delete'),
    path('section_update/<int:pk>/', section_update, name='section_update'),
    path('section_create', section_create, name='section_create'),

    # Article type
    path('article_types/', article_type_list, name='article_types'),
    path('article_types_delete/<int:pk>/', article_type_delete, name='article_type_delete'),
    path('article_type_update/<int:pk>/', article_type_update, name='article_type_update'),
    path('article_type_create', article_type_create, name='article_type_create'),

    # Article stage
    path('article_stages/', article_stages_list, name='article_stages'),
    path('article_stages_delete/<int:pk>/', article_stages_delete, name='article_stages_delete'),
    path('article_stages_update/<int:pk>/', article_stages_update, name='article_stages_update'),
    path('artilce_stages_create/', article_stages_create, name='article_stages_create'),

    # Notification status 
    path('notification_status/', notification_status_list, name='notification_status'),
    path('notification_status_delete/<int:pk>/', notification_status_delete, name='notification_delete'),
    path('notification_status_update/<int:pk>/', notification_status_update, name='notification_update'),
    path('notification_status_create/', notification_status_create, name='notification_create')

]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from article_app.views import set_language

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += i18n_patterns(

    path('_adminjon/', admin.site.urls),
    path('', include('article_app.urls')),
    path('profile/', include('user_app.urls')),
    path('journal/', include('journal.urls')),
    path('post/', include('post.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("set_language/<str:language>", set_language, name="set-language"),
    prefix_default_language=False,
)
urlpatterns += [
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.views import *

urlpatterns = [
    path('post_dashboard/', post_dashboard, name='post_dashboard'),
    path('page_dashboard/', page_dashboard, name='page_dashboard'),
    path('create_post/', create_post, name='create_post'),
    path('create_page/', create_page, name='create_page'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('edit_post/<int:pk>/', edit_post, name='edit_post'),
    path('delete_post/<int:pk>/', delete_post, name='delete_post'),
    path('edit_page/<int:pk>/', edit_page, name='edit_page'),
    path('delete_page/<int:pk>/', delete_page, name='delete_page'),
]

article_app/models.py
import os

from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Section(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)

    def __str__(self):
        return self.name


class ArticleType(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)

    def __str__(self):
        return self.name


class ArticleLanguage(models.Model):
    name = models.CharField(_('Name'), max_length=150, blank=True, default=None)

    def __str__(self):
        return self.name


class Stage(models.Model):
    name = models.CharField(_('Name'), max_length=100, default=None)

    def __str__(self):
        return self.name


class ArticleStatus(models.Model):
    name = models.CharField(max_length=100, default=None)
    stage = models.ForeignKey('article_app.Stage', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


def user_directory_path(instance, filename):
    return 'files/articles/{0}'.format(filename)


class Article(models.Model):
    article_type = models.ForeignKey('article_app.ArticleType', on_delete=models.CASCADE, blank=True)
    country = models.ForeignKey('user_app.Country', on_delete=models.CASCADE, blank=True)
    article_lang = models.ForeignKey('article_app.ArticleLanguage', on_delete=models.CASCADE, blank=True)
    section = models.ForeignKey('article_app.Section', verbose_name="Section", related_name="article_section",
                                on_delete=models.CASCADE, blank=True)
    author = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="article_author", blank=True)
    file = models.ForeignKey('article_app.ArticleFile', related_name="article_file", blank=True,
                             on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255, blank=True)
    title_en = models.CharField(max_length=255, blank=True)
    abstract = RichTextUploadingField(blank=True)
    abstract_en = RichTextUploadingField(blank=True)
    keywords = RichTextField(blank=True)
    keywords_en = RichTextField(blank=True)
    references = RichTextField(blank=True, null=True)
    article_status = models.ForeignKey('article_app.ArticleStatus', on_delete=models.CASCADE, blank=True, null=True)
    is_publish = models.BooleanField(default=False)
    is_resubmit = models.BooleanField(default=False)
    is_publish_journal = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    filePDF = models.FileField(_("Pdf Fayl"), upload_to="files/articles/%Y/%m/%d", blank=True, null=True,
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']


class ArticleFile(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    file = models.FileField(_("Word Fayl"), upload_to="files/articles/%Y/%m/%d", max_length=255, blank=True,
                            validators=[FileExtensionValidator(allowed_extensions=['doc', 'docx'])],
                            help_text='Please upload only .doc or .docx files!')
    file_status = models.SmallIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def file_name(self):
        return str(self.file.name.split("/")[-1].replace('_', ' ').replace('-', ' '))

    def file_size(self):
        return self.file.size

    def file_type(self):
        name, type_f = os.path.splitext(self.file.name)
        return type_f

    # def get_absolute_url(self):
    #     return reverse('article_app:document-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.article)


class ExtraAuthor(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    lname = models.CharField(max_length=50, blank=True)
    fname = models.CharField(max_length=50, blank=True)
    mname = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True)
    work = models.CharField(max_length=255, blank=True, null=True)
    scientific_degree = models.ForeignKey('user_app.ScientificDegree', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.fname


class NotificationStatus(models.Model):
    name = models.CharField(_('Name'), max_length=50, blank=True)

    def __str__(self):
        return self.name


class Notification(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, blank=True)
    from_user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="sender_user", blank=True,
                                  null=True)
    to_user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, related_name="recieve_user", blank=True,
                                null=True)
    message = models.TextField(_("Message"), blank=True)
    notification_status = models.ForeignKey('article_app.NotificationStatus', on_delete=models.CASCADE, blank=True,
                                            null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_update_article = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

templates/article_app/message/send_message.html
{% load i18n %}
{% load static %}
<form class="send-message-form" data-parsley-validate="true" method="post"
      action="{% url 'send_message' article.id user_id %}">
    {% csrf_token %}
    <div class="modal fade" id="send-message-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Xabar yuborish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr hidden>
                            <td class="text-nowrap">
                                <select id="id_article" name="article" class="form-control">
                                    <option selected
                                            value="{{ article.id }}">{{ article.id }}</option>
                                </select>
                            </td>
                        </tr>
                        <tr hidden>
                            <td class="text-nowrap">
                                <select id="id_from_user" name="from_user" class="form-control">
                                    <option selected
                                            value="{{ from_user.id }}">{{ from_user.id }}</option>
                                </select>
                            </td>
                        </tr>
                        <tr hidden>
                            <td class="text-nowrap">
                                <select id="id_to_user" name="to_user" class="form-control">
                                    <option selected
                                            value="{{ user_id }}">{{ user_id }}</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Xabar" %}</th>
                            <td class="text-nowrap">{{ form.message }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a class="close btn btn-outline-info"
                       data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        const $myForm = $('.send-message-form');
        $myForm.submit(function (e) {
            e.preventDefault();

            const $formData = $myForm.serialize();

            $.ajax({
                type: 'POST',
                url: "{% url 'send_message' article.id  user_id %}",
                data: $formData,
                success: function (response) {
                    if (response.result) {
                        $('#send-message-modal').modal('hide');

                        $('#view-article-messages-admin').click();
                        $('#view-article-messages-by-editor').click();
                        $('#view-article-messages-by-reviewer').click();
                        $('#view-article-messages-by-author_{{ article.id }}').click();

                    } else {
                        alert(response.message);
                    }
                },
                error: function (error) {
                    console.log(error);
                }
            });

        });
    });
</script>