config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from article_app.views import set_language

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += i18n_patterns(

    path('_adminjon/', admin.site.urls),
    path('', include('article_app.urls')),
    path('profile/', include('user_app.urls')),
    path('journal/', include('journal.urls')),
    path('post/', include('post.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("set_language/<str:language>", set_language, name="set-language"),
    prefix_default_language=False,
)
urlpatterns += [
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.views import *

urlpatterns = [
    path('post_dashboard/', post_dashboard, name='post_dashboard'),
    path('page_dashboard/', page_dashboard, name='page_dashboard'),
    path('create_post/', create_post, name='create_post'),
    path('create_page/', create_page, name='create_page'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('edit_post/<int:pk>/', edit_post, name='edit_post'),
    path('delete_post/<int:pk>/', delete_post, name='delete_post'),
    path('edit_page/<int:pk>/', edit_page, name='edit_page'),
    path('delete_page/<int:pk>/', delete_page, name='delete_page'),
]

user_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from user_app.views import *

urlpatterns = [
    path('user_dashboard/', user_dashboard, name='dashboard'),
    path('editor_dashboard/', editor_dashboard, name='editor_dashboard'),
    path('reviewer_dashboard/', reviewer_dashboard, name='reviewer_dashboard'),
    path('editor_notifications/', editor_notifications, name='editor_notifications'),
    path('reviewer_notifications/', reviewer_notifications, name='reviewer_notifications'),

    path('load_notif_count/', load_notif_count, name='load_notif_count'),

    path('editor_check_article/<int:pk>/', editor_check_article, name='editor_check_article'),
    path('editor_submit_result/', editor_submit_result, name='editor_submit_result'),

    path('reviewer_check_article/<int:pk>/', reviewer_check_article, name='reviewer_check_article'),

    path('article_notification/view/<int:pk>/', author_vs_editor_vs_reviewer, name='comment_author_vs_editor'),

    path('load_notif/', load_notification, name='load_notification'),
    path('count_notif/', count_notification, name='count_notification'),
    path('load_reviewers/', load_reviewers, name='load_reviewers'),
    path('sending_reviewer/', sending_reviewer, name='sending_reviewer'),
    path('random_sending_reviewer/', random_sending_reviewer, name='random_sending_reviewer'),

    path('reviewer_confirmed/', reviewer_confirmed, name='reviewer_confirmed'),
    path('reviewer_resubmit/', reviewer_resubmit, name='reviewer_resubmit'),
    path('reviewer_rejected/', reviewer_rejected, name='reviewer_rejected'),

    path('approve_publish/', approve_publish, name='approve_publish'),
    path('editor_resubmit_to_reviewer/', editor_resubmit_to_reviewer, name='editor_resubmit_to_reviewer'),

    path('login/', login_page, name='login'),
    path('logout', logout_user, name='logout'),
    path('register/', register_page, name='register'),
    path('choosen_reviewer_role/', choose_roles, name='choosen_reviewer_role'),
    path('choosen_reviewer_role_list/', reviewer_role_list, name='choosen_reviewer_role_list'),
    path('choosen_reviewer_role_list/<int:pk>/', reviewer_role_list_detail, name='reviewer_role_list_detail'),

    path('edit_profile/', edit_profile, name='edit_profile'),
    path('load_menus/', load_menus, name='load_menus'),
    path('reviewers_list/', reviewers_list, name='reviewers_list'),

    # Country
    path('countries/', countries_list, name='countries'),
    path('county_delete/<int:pk>/', country_delete, name='country-delete'),
    path('county_update/<int:pk>/', country_update, name='country-update'),
    path('county_create', country_create, name='country-create'),

    path('editors/', editors_list, name='editors'),
    path('editors/give_role/<int:pk>/', give_editor_role, name='give_editor_role'),

    # Region
    path('regions/', regions_list, name='regions'),
    path('region_delete/<int:pk>/', region_delete, name='regions_delete'),
    path('region_update/<int:pk>/', region_update, name='region-update'),
    path('region_create', region_create, name='region-create'),

    path('genders/', genders_list, name='genders'),
    path('menus/', menus_list, name='menus'),

    # Roles
    path('roles/', roles_list, name='roles'),
    path('role_delete/<int:pk>/', roles_delete, name='roles_delete'),
    path('role_update/<int:pk>/', roles_update, name='role_update'),
    
    path('scientific_degrees/', scientific_degrees_list, name='scientific_degrees'),
    path('users/', users_list, name='users'),
    path('users/view/<int:pk>/', view_user, name='view_user'),
    path('users/edit/<int:pk>/', edit_user, name='edit_user'),
    path('users/delete/<int:pk>/', delete_user, name='delete_user'),

    path('change_password/', change_password, name='change_password'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='user_app/register/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="user_app/register/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user_app/register/password_reset_complete.html'),
         name='password_reset_complete'),
]

user_app/models.py
import os

from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from user_app.validator import validate_file_size


class Country(models.Model):
    name = models.CharField(_('Name'), max_length=50)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(_('Name'), max_length=50)

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(_('Name'), max_length=10)

    def __str__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(_('Name'), max_length=255, unique=True)
    code_name = models.CharField(max_length=10, blank=True, null=True)
    level = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class User(AbstractUser):
    username = models.CharField(_("Username"), max_length=100, blank=True, unique=True)
    last_name = models.CharField(_('Surname'), max_length=100, blank=True)
    first_name = models.CharField(_('Name'), max_length=100, blank=True)
    middle_name = models.CharField(_('Middle Name'), max_length=30, null=True, blank=True)
    birthday = models.DateField(_('Birthday'), null=True, blank=True)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE, null=True, blank=True)
    avatar = models.ImageField(_("Avatar"), upload_to='avatars/%Y/%m/%d', default='user.png',
                               validators=[validate_file_size, FileExtensionValidator(['png', 'jpg'])], blank=True,
                               null=True)
    email = models.EmailField(_('Email address'), max_length=255, blank=True, unique=True)
    phone = models.CharField(max_length=20, null=True, blank=True, verbose_name='Phone number', unique=True)
    pser = models.CharField(_('Passport '), max_length=2, blank=True, null=True)
    pnum = models.CharField(_('Passport '), max_length=7, blank=True, null=True)
    work = models.CharField(max_length=255, null=True, blank=True)
    region = models.ForeignKey('user_app.Region', on_delete=models.CASCADE, verbose_name="Region", null=True,
                               blank=True)
    roles = models.ManyToManyField('user_app.Role', related_name="user_roles", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def full_name(self):
        if self.first_name is not None and self.last_name is not None:
            full_name_user = f"{self.last_name} {self.first_name}"
        else:
            full_name_user = f"{self.username}"
        return full_name_user

    @property
    def get_roles(self):
        roles = []
        levels = []
        for role in self.roles.all():
            roles.append(role.id)
            levels.append(role.level)
        return roles, levels

    def __str__(self):
        return self.username


class Editor(models.Model):
    user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, blank=True)
    is_editor = models.BooleanField(default=False)


class ScientificDegree(models.Model):
    name = models.CharField(max_length=255, blank=True, unique=True)
    level = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class Reviewer(models.Model):
    section = models.ManyToManyField('article_app.Section', related_name="reviewer_sections", blank=True)
    scientific_degree = models.ForeignKey('user_app.ScientificDegree', on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey('user_app.User', on_delete=models.CASCADE, blank=True, null=True)
    is_reviewer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ReviewerFile(models.Model):
    reviewer = models.ForeignKey('user_app.Reviewer', on_delete=models.CASCADE, blank=True)
    file = models.FileField(_("Fayl"), upload_to="files/reviewer/%Y/%m/%d", max_length=255, blank=True, null=True,
                            validators=[FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])],
                            help_text='Please upload only .doc, .docx or .pdf files!')

    def file_name(self):
        return str(self.file.name.split("/")[-1].replace('_', ' ').replace('-', ' '))

    def file_size(self):
        return self.file.size

    def file_type(self):
        name, type_f = os.path.splitext(self.file.name)
        return type_f


class ReviewerEditorStatus(models.Model):
    name = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


class ReviewerEditor(models.Model):
    reviewer = models.ForeignKey('user_app.Reviewer', blank=True, on_delete=models.CASCADE)
    editor = models.ForeignKey('user_app.Editor', on_delete=models.CASCADE, blank=True)
    status = models.ForeignKey('user_app.ReviewerEditorStatus', on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class StatusReview(models.Model):
    name = models.CharField(_('Name'), max_length=255, unique=True)

    def __str__(self):
        return self.name


class ReviewerArticle(models.Model):
    article = models.ForeignKey('article_app.Article', on_delete=models.CASCADE, related_name="review_article",
                                blank=True)
    editor = models.ForeignKey('user_app.Editor', on_delete=models.CASCADE, related_name="review_editor", blank=True)
    reviewer = models.ForeignKey('user_app.Reviewer', on_delete=models.CASCADE, related_name="review_reviewer",
                                 blank=True)
    status = models.ForeignKey('user_app.StatusReview', on_delete=models.CASCADE, related_name="review_status",
                               blank=True)
    comment = models.TextField()
    result = models.PositiveSmallIntegerField(default=0)
    is_extra = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Menu(models.Model):
    name = models.CharField(max_length=100)
    icon_name = models.CharField(max_length=255, null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    url_name = models.CharField(max_length=255, null=True, blank=True)
    order = models.PositiveSmallIntegerField(default=0)
    status = models.BooleanField(default=True)
    allowed_roles = models.ManyToManyField('user_app.Role', related_name='allowed_role_menus', blank=True)
    type = models.PositiveSmallIntegerField(default=0)

    def get_roles(self):
        return [p.name for p in self.allowed_roles.all()]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(f'{self.url_name}')

user_app/forms.py
from django import forms
from django.forms import Select, TextInput, SelectMultiple
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from user_app.models import *
from bootstrap_datepicker_plus.widgets import DatePickerInput


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'middle_name', 'username', 'email', 'password1', 'password2']


class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'middle_name', 'birthday', 'avatar', 'email',
                  'phone', 'pser', 'pnum', 'region', 'gender', 'work']

        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control first_name',
                'type': 'text',
                'placeholder': "Surname",
            }),
            'last_name': TextInput(attrs={
                'class': 'form-control last_name',
                'type': 'text',
                'placeholder': "Name",
            }),
            'middle_name': TextInput(attrs={
                'class': 'form-control middle_name',
                'type': 'text',
                'placeholder': "Middle",
            }),
            'username': TextInput(attrs={
                'class': 'form-control username',
                'type': 'text',
                'placeholder': "Username",
                'data - parsley - required': "true",
            }),
            'phone': TextInput(attrs={
                'class': 'form-control phone',
                'type': 'text',
                'id': 'masked-input-phone',
                'placeholder': 'Phone Number',
            }),
            'pser': TextInput(attrs={
                'class': 'form-control pser',
                'type': 'text',
                'id': 'masked-input-pasport',
                'placeholder': 'Passport Seria',
                'data - parsley - group': "step-1",
            }),
            'pnum': TextInput(attrs={
                'class': 'form-control pnum',
                'type': 'text',
                'id': 'masked-input-pasport',
                'placeholder': 'Passport Number',
            }),
            'email': TextInput(attrs={
                'class': 'form-control email',
                'type': 'email',
                'placeholder': 'Email',
            }),

            'region': Select(attrs={
                'class': 'form-control region',
                'data-live-search': "true",
                'data-style': "btn-white",
            }),
            'gender': Select(attrs={
                'class': 'form-control gender',
                'data-live-search': "true",
                'data-style': "btn-white",
            }),
            'work': TextInput(attrs={
                'class': 'form-control work',
                'type': 'text',
                'placeholder': 'Please enter your work',
            }),
            'birthday': DatePickerInput(attrs={
                'class': 'form-control birthday',
                'name': 'birthday',
            }),
        }


class ReviewerFileForm(forms.ModelForm):
    file = forms.FileField(
        label="Files",
        widget=forms.ClearableFileInput(attrs={"multiple": True, "name": "file"})
    )

    class Meta:
        model = ReviewerFile
        fields = ['file']


class AddReviewerForm(forms.ModelForm):
    class Meta:
        model = Reviewer
        fields = ['user', 'section', 'scientific_degree']

        widgets = {
            'section': SelectMultiple(attrs={
                'class': 'multiple-select2 form-control',
                'multiple': 'multiple',
                'placeholder': 'Select',
                'name': 'section',
            }),
            'scientific_degree': Select(attrs={
                'class': 'form-control selectpicker',
                'data-live-search': "true",
                'data-style': "btn-white",
                'name': 'scientific_degree',
            }),
        }

templates/user_app/crud/add_district.html
{% load i18n %}
{% load static %}
<form method="post" action="{% url 'create_district' %}">
    {% csrf_token %}
    <div class="modal fade" id="addUser">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi tuman qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Viloyat" %}</th>
                            <td class="text-nowrap">{{ form.region }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>

templates/user_app/crud/add_gender.html
{% load i18n %}
<form method="post" action="{% url 'create_gender' %}">
    {% csrf_token %}
    <div class="modal fade" id="addUser">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi jins qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Holat" %}</th>
                            <td class="text-nowrap">{{ form.status }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>

templates/user_app/crud/add_state.html
{% load i18n %}
<form method="post" action="{% url 'create_state' %}">
    {% csrf_token %}
    <div class="modal fade" id="addUser">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Yangi holat qo'shish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-striped table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Holat" %}</th>
                            <td class="text-nowrap">{{ form.status }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>

templates/user_app/crud/choose_role.html
{% load i18n %}
{% load static %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'choose_role' %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Saytga kim sifatida kirmoqchisiz?" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <select id="id_user" name="user" class="form-control" style="visibility: visible">
                                <option selected value="{{ user.id }}">{{ user.full_name }}</option>
                            </select>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Rolni tanlang:" %}</th>
                            <td class="text-nowrap"><label>Author
                                <input type="checkbox" value="0">
                            </label></td>
                            <td class="text-nowrap"><label>Reviewer
                                <input type="checkbox" value="1">
                            </label></td>
                        </tr>
                        <hr>
                        <tr>
                            <th class="text-nowrap">{% trans "Rukn" %}</th>
                            <td class="text-nowrap">{{ form.section }}</td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Fayl" %}</th>
                            <td class="text-nowrap">{{ form.mfile }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" style="float: right">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>

templates/user_app/crud/delete_district.html
{% load i18n %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'delete_district' district.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Tumanni o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ district.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/user_app/crud/delete_gender.html
{% load i18n %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'delete_gender' gender.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Jinsni o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ gender.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/user_app/crud/delete_region.html
{% load i18n %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'delete_region' region.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Viloyatni o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ region.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/user_app/crud/delete_role.html
{% load i18n %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'delete_role' role.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Rolni o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ role.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/user_app/crud/delete_state.html
{% load i18n %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'delete_state' state.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% trans "Holatni o'chirish" %}</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <strong>{{ state.name }}</strong><br>
                    <span style="font-size: small">{% trans "O'chirishga ishonchingiz komilmi?" %}</span>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yoq" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Ha" %}</button>
                </div>

            </div>
        </form>
    </div>
</div>

templates/user_app/crud/edit_district.html
{% load i18n %}
{% load static %}
<div class="modal fade" id="UserModal">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" action="{% url 'edit_district' district.id %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Tumanni o'zgartirish" %}</h5>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <table id="data-table-default"
                           class="table table-bordered table-td-valign-middle">
                        <tbody>
                        <tr>
                            <th class="text-nowrap">{% trans "Nomi" %}</th>
                            <td class="text-nowrap">{{ form.name }}</td>
                        </tr>
                        <tr>
                            <th class="text-nowrap">{% trans "Viloyat" %}</th>
                            <td class="text-nowrap">{{ form.region }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-white" data-dismiss="modal">{% trans "Yopish" %}</a>
                    <button type="submit" class="btn btn-primary">{% trans "Saqlash" %}</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="{% static '/assets/js/demo/form-plugins.demo.js' %}"></script>